name: q_app_new
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_svg: ^0.17.1
  positioned_tap_detector: ^1.0.3
  video_player: "0.5.1"
  
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    #home
      - lib/home_page_need/background.png
      - lib/home_page_need/white_logo_q.svg
      - lib/home_page_need/border_btn.svg
      - lib/home_page_need/Full_btn.svg
      - lib/home_page_need/startlogo.png
      - lib/home_page_need/startlogomusg.png
      #ABOUT
      - lib/About_page_need/background.png
      - lib/About_page_need/back_btn_about.svg
      - lib/About_page_need/aboutlogo.png
      - lib/About_page_need/tilLogo.png
      - lib/About_page_need/mifkada.png
      - lib/About_page_need/Mifkada2.png
      #start
      - lib/Start_page_need/Start_background.png
      - lib/Start_page_need/Back_btn.svg
      - lib/Start_page_need/_Select.svg
      - lib/Start_page_need/signal.svg
      - lib/Start_page_need/selectS.svg
      #Tironut02
      - 'lib/options_choose_page_need/Home_Btn.svg'
      - 'lib/options_choose_page_need/pop_up_y.svg'
      - 'lib/options_choose_page_need/pop_up_y.png'
      - 'lib/options_choose_page_need/Ipus.svg'
      - 'lib/options_choose_page_need/tironut_questions.png'
      - 'lib/tironut_questions.png'
      - 'lib/klia.png'
      - 'lib/options_choose_page_need/Ipus.jpeg'
      - 'lib/options_choose_page_need/IpusP.png'
      - 'lib/options_choose_page_need/klia.png'
      #Tirgul
      - 'lib/Tirgul_files/Tirgul/Yellowbackground.png'
      - 'lib/Tirgul_files/Tirgul/background_tirgul.png'
      - 'lib/Tirgul_files/Tirgul/Select_btn_black.svg'
      - 'lib/Tirgul_files/Tirgul/_tick.svg'
      - 'lib/Tirgul_files/Tirgul/_cross.svg'
      - 'lib/Tirgul_files/Tirgul/next.svg'
      - 'lib/Tirgul_files/Tirgul/graynext.svg'

      - 'lib/Tirgul_files/Tirgul/__tick.png'
      - 'lib/Tirgul_files/Tirgul/__cross.png'
      - 'lib/Tirgul_files/Tirgul/__next.png'
      - 'lib/Tirgul_files/Tirgul/__graynext.png'

     # - 'lib/Tirgul_files/Tirgul/DATA.json'
      # - 'package:q_app_new/assets/DATA.json'
      - 'assets/'
      - 'assets/TohenPic/'
      # - lib/Start_page_need/btn.svg
      # - lib/Start_page_need/select_.svg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
fonts:
    - family: Alef-Bold
      fonts:
        - asset: lib/Fonts/Alef-Bold.ttf
        - weight: 700
    - family: Alef
      fonts:
        - asset: lib/Fonts/Alef-Regular.ttf

  
